from enum import IntEnum


class PACKET_TYPES(IntEnum):
    USB_NONE = 0
    USB_MIC_DATA = 1
    USB_BLE_COMMAND = 2
    USB_BLE_INFO = 3
    USB_BLE_DEVICE_CONNECTED = 4
    USB_BLE_DEVICE_DISCONNECTED = 5
    USB_BLE_RECORDING_FINISHED = 6
    USB_INFO = 7
    USB_SENSOR_DATA = 8
    USB_BLE_DATABASE_DISCOVERY_COMPLETE = 9
    USB_BLE_STATUS_UPDATE = 10

class BLE_INFO(IntEnum):
    BLE_TX_FINISHED = 0

class BLE_COMMANDS(IntEnum):
    BLE_GATT_REQUEST = 0
    BLE_SCAN_START = 1
    BLE_SCAN_STOP = 2
    BLE_TX_AWAIT_FINISHED = 3

class BLE_GATT_COMMANDS(IntEnum):
    BLE_START_NOTIFICATIONS = 0
    BLE_STOP_NOTIFICATIONS = 1
    BLE_WRITE_CHARACTERISTIC = 2
    BLE_READ_CHARACTERISTIC = 3

class SENSOR_TYPES(IntEnum):
    SENSOR_FG = 0 # Fuel Gauge
    SENSOR_ACCEL = 1
    SENSOR_MAG = 2
    SENSOR_GYRO = 3
    SENSOR_MICROPHONE = 4
    
class STATUS_UPDATE_TYPES(IntEnum):
    DCS_XCORR_UPDATE = 0
    DCS_STATUS_MILESTONE_REACHED = 1
    DCS_STATUS_MOTION_CORRECTED = 2
    DCS_STATUS_NEXT_MILESTONE = 3
    DCS_STATUS_NAV_TRANSITION= 4
    DCS_STATUS_NAV_END = 5
    DCS_STATUS_LOG = 6
    DCS_STATUS_CONNECTION_INTERVAL_UPDATE = 7
    DCS_STATUS_CALIBRATION_DONE = 8
    DCS_STATUS_COLLISION_DETECTED = 9
    DCS_IR_STATUS_UPDATED = 10
    DCS_STATUS_BASE_ENTERED = 11
    DCS_STATUS_PING = 12

class MOTION_FLAGS(IntEnum):
    FORCE_UPDATE = 0
    UPDATE_ANGLE = 1